############################# Lightning's Weapons #############################
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (3, 'Omega Weapon', 47, 100, 16962, 297, 11355, null, null, 'Independent', null, null, 12800, null, 'Blazefire Saber');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (2, 'Flamberge', 10, 61, 3435, 215, 3360, 10, null, 'Physical Defense', null, null, 4000, 3, 'Blazefire Saber');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (1, 'Blazefire Saber', 1, 26, 300, 57, 0, 4, null, 'Physical Defense', 'Up in Arms', 2000, 1000, 2, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (6, 'Omega Weapon', 39, 100, 14586, 297, 13389, null, 'Attack: ATB Charge 2', 'Independent', null, null, 34125, null, 'Axis Blade');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (5, 'Enkindler', 13, 41, 6732, 261, 6324, 10, 'Attack: ATB Charge 2', 'Boost', null, null, 19500, 6, 'Axis Blade');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (4, 'Axis Blade', 1, 21, 1200, 225, 0, 8, 'Attack: ATB Charge', 'Boost', 'Plautus''s Workshop', 15000, 7500, 5, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (9, 'Omega Weapon', 47, 100, 16962, 297, 11355,  null, null, 'Independent', null, null, 29400, null, 'Edged Carbine');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (8, 'Razor Carbine', 11, 61, 4080, 215, 810, 10,  null, 'Magic Defense', null, null, 9200, 9, 'Edged Carbine');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (7, 'Edged Carbine', 1, 26, 420, 75, 0, 4, null, 'Magic Defense', 'Up in Arms', 4600, 2300, 8, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (12, 'Omega Weapon', 37, 100, 13992, 297, 1290, null, 'Improved Raise 2', 'Independent', null, null, 45500, null, 'Lifesaber');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (11, 'Peacemaker', 16, 41, 6600, 240, 650, 10, 'Improved Raise 2', 'Low HP', null, null, 26000, 12, 'Lifesaber');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (10, 'Lifesaber', 1, 21, 1500, 215, 0, 7, 'Improved Raise', 'Low HP', 'Plautus''s Workshop', 20000, 10000, 11, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (15, 'Omega Weapon', 42, 100, 15477, 297, 8520, null, null, 'Independent', null, null, 45440, null, 'Gladius');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (14, 'Helter-skelter', 19, 61, 4524, 168, 2096, 10, null, 'Physical Defense', null, null, 14200, 15, 'Gladius');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (13, 'Gladius', 1, 26, 800, 116, 0, 5, null, 'Physical Defense', 'Up in Arms', 7100, 3550, 14, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (18, 'Omega Weapon', 11, 100, 12804, 297, 408, null, 'Ironstrike', 'Independent', null, null, 63700, null, 'Organyx');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (17, 'Apocalypse', 14, 61, 2308, 116, 652, 10, 'Ironstrike', 'Adamancy', null, null, 36400, 18, 'Organyx');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (16, 'Organyx', 1, 26, 300, 42, 0, 3, 'Leaderstrike', 'Adamancy', 'Gilgamesh, Inc.', 280000, 14000, 17, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (21, 'Omega Weapon', 42, 100, 15477, 297, 8520, null, 'Stagger Lock', 'Independent', null, null, 45500, null, 'Hauteclaire');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (20, 'Durandal', 19, 61, 4524, 168, 2096, 10, 'Stagger Lock', 'Gestalt', null, null, 26000, 21, 'Hauteclaire');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (19, 'Hauteclaire', 1, 26, 800, 116, 0, 5, 'Stagger Lock', 'Gestalt', 'Gilgamesh, Inc.', 20000, 10000, 20, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (24, 'Omega Weapon', 35, 100, 13398, 297, 6143, null, 'Quick Stagger', 'Independent', null, null, 63700, null, 'Lionheart');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (23, 'Ultima Weapon', 15, 41, 5848, 232, 5548, 10, 'Quick Stagger', 'Gestalt', null, null, 36400, 24, 'Lionheart');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (22, 'Lionheart', 1, 21, 1500, 174, 0, 7, 'Quick Stagger', 'Gestalt', 'Plautus''s Workshop', 28000, 14000, 23, null);

############################# Sahz's Weapons #############################
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (27, 'Total Eclipses', 34, 100, 18612, 363, 10992, null, null, 'Independent', null, null, 12800, null, 'Vega 42s');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (26, 'Altairs', 10, 61, 3435, 215, 3360, 10, null, 'Magic Defense', null, null, 4000, 27, 'Vega 42s');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (25, 'Vega 42s', 1, 26, 300, 57, 0, 4, null, 'Magic Defense', 'Up in Arms', 2000, 1000, 26, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (30, 'Total Eclipses', 16, 100, 14619, 363, 6176, null, 'Augment Maintenance 2', 'Independent', null, null, 32987, null, 'Spica Defenders');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (29, 'Sirius Sidearms', 16, 41, 6080, 232, 3390, 10, 'Augment Maintenance 2', 'Positive Effect', null, null, 18850, 30, 'Spica Defenders');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (28, 'Spica Defenders', 1, 21, 1200, 225, 0, 7, 'Augment Maintenance', 'Positive Effect', 'Plautus''s Workshop', 14500, 7250, 29, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (33, 'Total Eclipses', 45, 100, 18612, 363, 2685, null, null, 'Independent', null, null, 24960, null, 'Deneb Duelers');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (32, 'Canopus AMPs', 13, 61, 4080, 215, 810, 10, null, 'Magic Defense', null, null, 7800, 33, 'Deneb Duelers');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (31, 'Deneb Duelers', 1, 26, 420, 75, 0, 4, null, 'Magic Defense', 'Up in Arms', 3900, 1950, 32, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (36, 'Total Eclipses', 40, 100, 16797, 363, 15417, null, null, 'Independent', null, null, 43255, null, 'Rigels');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (35, 'Polaris Specials', 19, 61, 4524, 168, 15417, 10, 'Stagger Lock', 'Gestalt', null, null, 24700, 36, 'Rigels');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (34, 'Rigels', 1, 26, 800, 116, 0, 5, 'Stagger Lock', 'Gestalt', 'Gilgamesh, Inc.', 19000, 9500, 35, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (39, 'Total Eclipses', 32, 100, 13893, 363, 2685, null, 'Ironstrike', 'Independent', null, null, 59832, null, 'Aldbarans');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (38, 'Sadalmeliks', 14, 61, 2308, 116, 652, 10, 'Ironstrike', 'Adamancy', null, null, 34190, 39, 'Aldbarans');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (37, 'Aldbarans', 1, 26, 300, 112, 0, 3, 'Leaderstrike', 'Adamancy', 'Gilgamesh, Inc.', 263000, 13150, 38, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (42, 'Total Eclipses', 45, 100, 18612, 363, 10992, null, 'Silk Tiger', 'Independent', null, null, 50050, null, 'Pleiades Hi-Powers');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (41, 'Hyades Magnums', 13, 61, 4080, 215, 810, 10, 'Silk Tiger', 'Damage Reduction', null, null, 28600, 42, 'Pleiades Hi-Powers');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (40, 'Pleiades Hi-Powers', 1, 26, 420, 75, 0, 4, 'Paper Tiger', 'Damage Reduction', 'Gilgamesh, Inc.', 22000, 11000, 41, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (45, 'Total Eclipses', 27, 100, 12078, 363, 4425, null, 'Chain Bonus Boost 2', 'Independent', null, null, 50050, null, 'Antares Deluxes');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (44, 'Fomalhaut Elites', 15, 41, 3852, 168, 1752, 10, 'Chain Bonus Boost 2', 'Boost', null, null, 28600, 45, 'Antares Deluxes');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (43, 'Antares Deluxes', 1, 21, 800, 116, 0, 5, 'Chain Bonus Boost', 'Boost', 'Plautus''s Workshop', 22000, 11000, 44, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (48, 'Total Eclipses', 35, 100, 14982, 363, 13397, null, 'Stagger Maintenance', 'Independent', null, null, 68250, null, 'Procyons');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (47, 'Betelgeuse Customs', 15, 41, 6240, 260, 3000, 10, 'Stagger Maintenance 2', 'Gestalt', null, null, 39000, 48, 'Procyons');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES (46, 'Procyons', 1, 21, 1500, 174, 0, 9, 'Stagger Maintenance', 'Gestalt', 'Plautus''s Workshop', 30000, 1500, 47, null);

############################# Hope's Weapons #####################################

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(51, 'Nue', 28, 100, 10384, 242, 2148, null, 'Critical: Shield 2', 'Independent', null, null, 28160, null, 'Airwing');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(50, 'Skycutter', 10, 41, 3012, 168, 2892, 10, 'Critical: Shield 2', 'Low HP', null, null, 13000, 51, 'Airwing');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(49, 'Airwing', 1, 21, 400, 76, 0, 5, 'Critical: Shield', 'Low HP', 'Plautus''s Workshop', 1000, 5000, 50, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(54,  'Nue', 49, 100, 15466, 242, 12774, null, null, 'Independent', null, null, 22750, null, 'Hawkeye');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(53,  'Eagletalon', 13, 61, 4080, 215, 810, 10, null, 'Magic Defense', null, null, 8800, 54, 'Hawkeye');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(52,  'Hawkeye', 1, 26, 420, 75, 0, 4, null, 'Magic Defense', 'Up in Arms', 4400, 2200, 53, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(57,  'Nue', 36, 100, 12320, 242, 6220, null, 'Siphon Boost 2', 'Independent', null, null, 64155, null, 'Otshirvani');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(56,  'Urubutsin', 16, 41, 6080, 232, 3390, 10, 'Siphon Boost 2', 'Boost', null, null, 36660, 57, 'Otshirvani');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(55,  'Otshirvani', 1, 21, 1200, 225, 0, 7, 'Siphon Boost', 'Boost', 'Plautus''s Workshop', 28200, 14100, 56, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(60,  'Nue', 49, 100, 15466, 242, 12774, null, null, 'Independent', null, null, 17920, null, 'Ninurta');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(59,  'Jatayu', 13, 61, 4080, 215, 810, 10, null, 'Physical Defense', null, null, 5600, 60, 'Ninurta');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(58,  'Ninurta', 1, 26, 420, 75, 0, 4, null, 'Physical Defense', 'Up in Arms', 2800, 1400, 59, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(63,  'Nue', 36, 100, 12320, 242, 6220, null, 'Defense Maintenance 2', 'Independent', null, null, 38447, null, 'Vidofnir');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(62,  'Hresvelgr', 16, 41, 6080, 232, 3390, 10, 'Defense Maintenance 2', 'Positive Effect', null, null, 21970, 63, 'Vidofnir');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(61,  'Vidofnir', 1, 21, 1200, 225, 0, 7, 'Defense Maintenance', 'Positive Effect', 'Plautus''s Workshop', 16900, 8450, 62, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(66,  'Nue', 28, 100, 10384, 242, 2148, null, 'Stifled Magic', 'Independent', null, null, 48230, null, 'Simurgh');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(65,  'Texcatlipoca', 15, 41, 3852, 168, 1762, 10, 'Stifled Magic', 'Ultimate Physique', null, null, 27560, 66, 'Simurgh');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(64,  'Simurgh', 1, 21, 800, 116, 0, 5, 'Stifled Magic', 'Ultimate Physique', 'Gilgamesh, Inc.', 21000, 10600, 65, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(69,  'Nue', 49, 100, 15466, 242, 12774, null, 'Silk Tiger', 'Independent', null, null, 45045, null, 'Malphas');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(68,  'Naberius', 13, 61, 4080, 215, 810, 10, 'Silk Tiger', 'Damage Reduction', null, null, 25740, 69, 'Malphas');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(67,  'Malphas', 1, 26, 420, 75, 0, 4, 'Paper Tiger', 'Damage Reduction', 'Gilgamesh, Inc.', 198000, 9900, 68, null);

INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(72,  'Nue', 44, 100, 14256, 242, 3284, null, 'Stagger Lock', 'Independent', null, null, 40950, null, 'Alicanto');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(71,  'Caldrius', 19, 61, 4524, 168, 2096, 10, 'Stagger Lock', 'Gestalt', null, null, 23400, 72, 'Alicanto');
INSERT INTO `ff13`.`item` (`item_id`, `item_name`, `item_min_level`, `item_max_level`, `item_base_xp`, `item_incremental_xp`, `item_xp_offset`, `item_catalyst`, `item_special_property`, `item_synthesis_group`, `item_shop`, `item_buy_price`, `item_sell_price`, `item_upgrade`, `item_item_group`)VALUES(70,  'Alicanto', 1, 26, 800, 116, 0, 5, 'Stagger Lock', 'Gestalt', 'Gilgamesh, Inc.', 18000, 9000, 71, null);
